export const USER_ADD_SKILLS_REQUEST = 'USER_ADD_SKILLS_REQUEST'
export const USER_ADD_SKILLS_SUCCESS = 'USER_ADD_SKILLS_SUCCESS'
export const USER_ADD_SKILLS_ERR = 'USER_ADD_SKILLS_ERR'

export const UPDATE_USER_STATS = 'UPDATE_USER_STATS';
