export const CREATE_PROJECT_REQUEST ='CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCESS';
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';

export const JOIN_PROJECT_REQUEST = 'JOIN_PROJECT_REQUEST';
export const JOIN_PROJECT_SUCCESS = 'JOIN_PROJECT_SUCESS';
export const JOIN_PROJECT_ERROR = 'JOIN_PROJECT_ERROR';


export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';


export const NEW_CHAT_MESSAGE = 'NEW_CHAT_MESSAGE';
export const SET_LAST_ACTIVITY = 'SET_LAST_ACTIVITY';
export const SET_UNREAD = 'SET_UNREAD';

export const EDIT_PROJECT_REQUEST = 'EDIT_PROJECT_REQUEST';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';
export const EDIT_PROJECT_ERROR = 'EDIT_PROJECT_ERROR';
